FI.WebAtividadeEntrevista/Controllers/BeneficiarioController.cs
using FI.AtividadeEntrevista.BLL;
using FI.AtividadeEntrevista.DML;
using FI.WebAtividadeEntrevista.Resources;
using FI.WebAtividadeEntrevista.Validators;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebAtividadeEntrevista.Models;

namespace WebAtividadeEntrevista.Controllers
{
    public class BeneficiarioController : Controller
    {
        [HttpPost]
        public JsonResult IncluirBeneficiario(BeneficiarioModel model)
        {
            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }

            if (!CPFValidator.IsValidCpf(model.CPF))
                return Json(new { success = false, message = BeneficiarioMsg.EXC0001 });

            BoBeneficiario boBeneficiario = new BoBeneficiario();

            model.Id = boBeneficiario.Incluir(new Beneficiario()
            {
                CPF = model.CPF,
                Nome = model.Nome,
                IdCliente = model.IdCliente
            });

            return Json(BeneficiarioMsg.INF0001);
        }

        [HttpPost]
        public JsonResult AtualizarBeneficiario(BeneficiarioModel model)
        {
            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }

            if (!CPFValidator.IsValidCpf(model.CPF))
                return Json(new { success = false, message = BeneficiarioMsg.EXC0001 });

            BoBeneficiario boBeneficiarios = new BoBeneficiario();

            boBeneficiarios.Alterar(new Beneficiario()
            {
                CPF = model.CPF,
                Nome = model.Nome,
                IdCliente = model.IdCliente,
                Id = model.Id
            });

            return Json(new { success = true, message = ClienteMsg.INF0001 });
        }

        [HttpPost]
        public JsonResult RemoveBeneficiario(long id)
        {
            try
            {
                BoBeneficiario boBeneficiario = new BoBeneficiario();
                boBeneficiario.Excluir(id);
                return Json(BeneficiarioMsg.INF0002);
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult GetBeneficiarios(long idCliente)
        {
            try
            {
                List<Beneficiario> beneficiario = new BoBeneficiario().Listar(idCliente);
                return Json(beneficiario, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

FI.WebAtividadeEntrevista/Controllers/ClienteController.cs
using FI.AtividadeEntrevista.BLL;
using FI.AtividadeEntrevista.DML;
using FI.WebAtividadeEntrevista.Resources;
using FI.WebAtividadeEntrevista.Validators;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebAtividadeEntrevista.Models;

namespace WebAtividadeEntrevista.Controllers
{
    public class ClienteController : Controller
    {
        private static List<Beneficiario> beneficiarios = new List<Beneficiario>();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Incluir()
        {
            beneficiarios.Clear();
            return View();
        }

        [HttpPost]
        public JsonResult Incluir(ClienteModel model)
        {
            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }

            if (!CPFValidator.IsValidCpf(model.CPF))
                return Json(new { success = false, message = BeneficiarioMsg.EXC0001 });

            BoCliente boCliente = new BoCliente();

            if (!boCliente.VerificarExistencia(model.CPF))
            {
                BoBeneficiario boBeneficiarios = new BoBeneficiario();

                model.Id = boCliente.Incluir(new Cliente()
                {
                    CEP = model.CEP,
                    CPF = model.CPF,
                    Cidade = model.Cidade,
                    Email = model.Email,
                    Estado = model.Estado,
                    Logradouro = model.Logradouro,
                    Nacionalidade = model.Nacionalidade,
                    Nome = model.Nome,
                    Sobrenome = model.Sobrenome,
                    Telefone = model.Telefone
                });

                if (beneficiarios.Count > 0)
                {
                    foreach (Beneficiario beneficiario in beneficiarios)
                    {
                        beneficiario.IdCliente = model.Id;
                        boBeneficiarios.Incluir(beneficiario);
                    }
                }
                return Json(ClienteMsg.INF0001);
            }
            else
                return Json(new { success = false, message = ClienteMsg.EXC0002 });
        }

        [HttpPost]
        public JsonResult Alterar(ClienteModel model)
        {
            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }

            BoCliente boCliente = new BoCliente();
            BoBeneficiario boBeneficiario = new BoBeneficiario();

            boCliente.Alterar(new Cliente()
            {
                Id = model.Id,
                CEP = model.CEP,
                CPF = model.CPF,
                Cidade = model.Cidade,
                Email = model.Email,
                Estado = model.Estado,
                Logradouro = model.Logradouro,
                Nacionalidade = model.Nacionalidade,
                Nome = model.Nome,
                Sobrenome = model.Sobrenome,
                Telefone = model.Telefone
            });

            if (beneficiarios.Count > 0)
                foreach (Beneficiario beneficiario in beneficiarios)
                {
                    if (beneficiario.Id == 0)
                        boBeneficiario.Incluir(beneficiario);
                }

            return Json(new { success = true, message = ClienteMsg.INF0001 });
        }

        [HttpGet]
        public ActionResult Alterar(long id)
        {
            BoCliente boCliente = new BoCliente();
            Cliente cliente = boCliente.Consultar(id);
            ClienteModel model = null;
            beneficiarios = new BoBeneficiario().Listar(id);

            if (cliente != null)
            {
                model = new ClienteModel()
                {
                    Id = cliente.Id,
                    CEP = cliente.CEP,
                    Cidade = cliente.Cidade,
                    Email = cliente.Email,
                    Estado = cliente.Estado,
                    Logradouro = cliente.Logradouro,
                    Nacionalidade = cliente.Nacionalidade,
                    Nome = cliente.Nome,
                    Sobrenome = cliente.Sobrenome,
                    Telefone = cliente.Telefone,
                    CPF = cliente.CPF
                };
            }
            return View(model);
        }

        [HttpPost]
        public JsonResult ClienteList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                int qtd = 0;
                string campo = string.Empty;
                string crescente = string.Empty;
                string[] array = jtSorting.Split(' ');

                if (array.Length > 0)
                    campo = array[0];

                if (array.Length > 1)
                    crescente = array[1];

                List<Cliente> clientes = new BoCliente().Pesquisa(jtStartIndex, jtPageSize, campo, crescente.Equals("ASC", StringComparison.InvariantCultureIgnoreCase), out qtd);
                return Json(new { Result = "OK", Records = clientes, TotalRecordCount = qtd });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult AdicionarBeneficiario(Beneficiario beneficiario)
        {
            BoCliente boCliente = new BoCliente();

            if (!CPFValidator.IsValidCpf(beneficiario.CPF))
                return Json(new { success = false, message = BeneficiarioMsg.EXC0001 });

            if (beneficiario.IdCliente != 0)
            {
                if (!boCliente.VerificarExistencia(beneficiario.CPF) && !verificarBeneficiarioCPF(beneficiario.CPF))
                {
                    beneficiarios.Add(beneficiario);
                    return Json(new { success = true, data = beneficiarios });
                }
                else
                    return Json(new { success = false, message = BeneficiarioMsg.EXC0002 });
            }
            else
            {
                if (verificarBeneficiarioCPF(beneficiario.CPF))
                    return Json(new { success = false, message = BeneficiarioMsg.EXC0002 });
                else
                {
                    beneficiarios.Add(beneficiario);
                    return Json(new { success = true, data = beneficiarios });
                }
            }
        }

        [HttpPost]
        public JsonResult DeleteBeneficiario(BeneficiarioModel model)
        {
            BoBeneficiario boBeneficiario = new BoBeneficiario();
            var beneficiario = beneficiarios.FirstOrDefault(b => b.Id == model.Id);

            if (model.Id > 0)
                boBeneficiario.Excluir(model.Id);

            beneficiarios.Remove(beneficiario);
            return Json(beneficiarios);
        }

        public bool verificarBeneficiarioCPF(string cpf)
        {
            var beneficiario = beneficiarios.FirstOrDefault(benificiario => benificiario.CPF == cpf);
            return beneficiario != null;
        }
    }
}

FI.WebAtividadeEntrevista/Views/Shared/_BeneficiarioModal.cshtml
@{
    ViewBag.Title = "Cadastrar Beneficiario";
}

@section scripts{
    <script>
        var urlPost = '@Url.Action("IncluirBeneficiario", "Beneficiario", new { area = "" })';
        var urlAlteracao = '@Url.Action("AtualizarBeneficiario", "Beneficiario", new { area = "" })';
        var urlExclusao = '@Url.Action("RemoveBeneficiario", "Beneficiario", new { area = "" })';
        var urlGetBeneficiarios = '@Url.Action("GetBeneficiarios", "Beneficiario", new { area = "" })';
    </script>

    @Scripts.Render("~/bundles/beneficiarios")
}

<form id="formNovoBeneficiario" method="post">
    <div class="row">
        <div class="col-md-5">
            <div class="form-group">
                <label for="CPF">CPF:</label>
                <input required="required" type="text" class="form-control cpf-mask" id="CPF" name="CPF" placeholder="Ex.: 999.999.999-99" maxlength="14">
            </div>
        </div>
        <div class="col-md-5">
            <div class="form-group">
                <label for="Nome">Nome:</label>
                <input required="required" type="text" class="form-control" id="Nome" name="Nome" placeholder="Ex.: João" maxlength="50">
            </div>
        </div>
        <div class="col-md-2">
            <div class="pull-right">
                <button type="submit" class="btn btn-sm btn-success">Incluir</button>
            </div>
        </div>
    </div>
</form>

FI.WebAtividadeEntrevista/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/jtable")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Clientes", "Index", "Cliente", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jtable")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>